load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

scala_library(
    name = "echo-service",
    srcs = ["Echo.scala"],
    visibility = ["//src/main/scala/com/example:__pkg__"]
)